<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>1701;1702;1591;8632</NoWarn>
    <DocumentationFile></DocumentationFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Configuration\APIJSON.json" />
    <None Remove="Configuration\App.json" />
    <None Remove="Configuration\Cache.json" />
    <None Remove="Configuration\Captcha.json" />
    <None Remove="Configuration\CodeGen.json" />
    <None Remove="Configuration\Database.json" />
    <None Remove="Configuration\Dji.json" />
    <None Remove="Configuration\Email.json" />
    <None Remove="Configuration\Enum.json" />
    <None Remove="Configuration\JWT.json" />
    <None Remove="Configuration\OAuth.json" />
    <None Remove="Configuration\Sms.json" />
    <None Remove="Configuration\Swagger.json" />
    <None Remove="Configuration\Upload.json" />
    <None Remove="Configuration\Wechat.json" />
    <None Remove="Dji.Application.xml" />
    <None Remove="Configuration\Limit.json" />
    <None Remove="Configuration\Logging.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\Logging.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Limit.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\APIJSON.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\App.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Cache.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Captcha.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\CodeGen.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Database.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Dji.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Email.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Enum.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\JWT.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\OAuth.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Sms.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Swagger.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Upload.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Configuration\Wechat.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dji.Core\Dji.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configuration\Hms.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Update="Configuration\OSS.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.0.1.1416" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Cloud\Dto\Wayline\" />
  </ItemGroup>

</Project>
