<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>Dji 程序集扫描和代码分析拓展插件。</Description>
		<TargetFramework>net10.0</TargetFramework>
		<NoWarn>1701;1702;1591;8632</NoWarn>
		<DocumentationFile></DocumentationFile>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net5.0' ">
		<PackageReference Include="Ben.Demystifier" Version="0.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="5.0.17" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.12" />
		<PackageReference Include="System.Text.Json" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
		<PackageReference Include="Ben.Demystifier" Version="0.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.25" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.12" />
		<PackageReference Include="System.Text.Json" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
		<PackageReference Include="Ben.Demystifier" Version="0.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.25" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.12" />
		<PackageReference Include="System.Text.Json" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
		<PackageReference Include="Ben.Demystifier" Version="0.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.35" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.12" />
		<PackageReference Include="System.Text.Json" Version="10.0.12" />
	</ItemGroup>

</Project>